/** 国家代码（ISO 3166-1 alpha-2）→ 英文国家名（基准表，无翻译时兜底） */

export const countryNamesEn: Record<string, string> = {
  US: 'United States',
  GB: 'United Kingdom',
  AU: 'Australia',
  CA: 'Canada',
  ZA: 'South Africa',
  AE: 'United Arab Emirates',
  ET: 'Ethiopia',
  IN: 'India',
  SA: 'Saudi Arabia',
  DE: 'Germany',
  FR: 'France',
  ES: 'Spain',
  IT: 'Italy',
  PT: 'Portugal',
  PL: 'Poland',
  RU: 'Russia',
  NL: 'Netherlands',
  TR: 'Turkey',
  CN: 'China',
  JP: 'Japan',
  KR: 'South Korea',
  SE: 'Sweden',
  NO: 'Norway',
  DK: 'Denmark',
  FI: 'Finland',
  IL: 'Israel',
  AL: 'Albania',
  AZ: 'Azerbaijan',
  BA: 'Bosnia and Herzegovina',
  BG: 'Bulgaria',
  MM: 'Myanmar',
  HR: 'Croatia',
  CZ: 'Czech Republic',
  EE: 'Estonia',
  PH: 'Philippines',
  GE: 'Georgia',
  GR: 'Greece',
  HU: 'Hungary',
  IS: 'Iceland',
  ID: 'Indonesia',
  IE: 'Ireland',
  KZ: 'Kazakhstan',
  KH: 'Cambodia',
  LA: 'Laos',
  LV: 'Latvia',
  LT: 'Lithuania',
  MK: 'North Macedonia',
  MY: 'Malaysia',
  MT: 'Malta',
  MN: 'Mongolia',
  NP: 'Nepal',
  AF: 'Afghanistan',
  IR: 'Iran',
  RO: 'Romania',
  RS: 'Serbia',
  LK: 'Sri Lanka',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SO: 'Somalia',
  TH: 'Thailand',
  UA: 'Ukraine',
  UZ: 'Uzbekistan',
  VN: 'Vietnam',
  BD: 'Bangladesh',
  KE: 'Kenya',
  NG: 'Nigeria',
  GH: 'Ghana',
  TZ: 'Tanzania',
  NZ: 'New Zealand',
  SG: 'Singapore',
  HK: 'Hong Kong',
  PK: 'Pakistan',
  EG: 'Egypt',
  MA: 'Morocco',
  LB: 'Lebanon',
  JO: 'Jordan',
  KW: 'Kuwait',
  QA: 'Qatar',
  BH: 'Bahrain',
  OM: 'Oman',
  YE: 'Yemen',
  IQ: 'Iraq',
  SY: 'Syria',
  LY: 'Libya',
  TN: 'Tunisia',
  DZ: 'Algeria',
  PS: 'Palestine',
  RW: 'Rwanda',
  UG: 'Uganda',
  ZW: 'Zimbabwe',
  BW: 'Botswana',
  NA: 'Namibia',
  MZ: 'Mozambique',
  ZM: 'Zambia',
  MW: 'Malawi',
  SS: 'South Sudan',
  SD: 'Sudan',
  MU: 'Mauritius',
  SC: 'Seychelles',
  CY: 'Cyprus',
  LU: 'Luxembourg',
  AT: 'Austria',
  CH: 'Switzerland',
  BE: 'Belgium',
  PR: 'Puerto Rico',
  CO: 'Colombia',
  AR: 'Argentina',
  BR: 'Brazil',
  MX: 'Mexico',
  CL: 'Chile',
  PE: 'Peru',
  EC: 'Ecuador',
  VE: 'Venezuela',
  HN: 'Honduras',
  GT: 'Guatemala',
  CR: 'Costa Rica',
  PA: 'Panama',
  DO: 'Dominican Republic',
  CU: 'Cuba',
  JM: 'Jamaica',
  TT: 'Trinidad and Tobago',
  BS: 'Bahamas',
  AM: 'Armenia',
  BO: 'Bolivia',
  GQ: 'Equatorial Guinea',
  NI: 'Nicaragua',
  PY: 'Paraguay',
  SV: 'El Salvador',
  UY: 'Uruguay',
  TW: 'Taiwan',
};
