/** 丹麦语（da）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameDa = {
  English: 'Engelsk',
  Arabic: 'Arabisk',
  Chinese: 'Kinesisk',
  Danish: 'Dansk',
  Dutch: 'Hollandsk',
  Finnish: 'Finsk',
  French: 'Fransk',
  German: 'Tysk',
  Greek: 'Græsk',
  Hebrew: 'Hebraisk',
  Hindi: 'Hindi',
  Italian: 'Italiensk',
  Japanese: 'Japansk',
  Korean: 'Koreansk',
  Norwegian: 'Norsk',
  Polish: 'Polsk',
  Portuguese: 'Portugisisk',
  Romanian: 'Rumænsk',
  Russian: 'Russisk',
  Spanish: 'Spansk',
  Swedish: 'Svensk',
  Thai: 'Thai',
  Turkish: 'Tyrkisk',
  Ukrainian: 'Ukrainsk',
  Vietnamese: 'Vietnamesisk',
};

export const countryNamesDa = {
  US: 'USA',
  GB: 'Storbritannien',
  AU: 'Australien',
  CA: 'Canada',
  ZA: 'Sydafrika',
  IN: 'Indien',
  DE: 'Tyskland',
  FR: 'Frankrig',
  ES: 'Spanien',
  IT: 'Italien',
  PT: 'Portugal',
  PL: 'Polen',
  RU: 'Rusland',
  NL: 'Holland',
  TR: 'Tyrkiet',
  CN: 'Kina',
  JP: 'Japan',
  KR: 'Sydkorea',
  SE: 'Sverige',
  NO: 'Norge',
  DK: 'Danmark',
  FI: 'Finland',
  IL: 'Israel',
  AT: 'Østrig',
  CH: 'Schweiz',
  BE: 'Belgien',
  IE: 'Irland',
  NZ: 'New Zealand',
  SG: 'Singapore',
  MX: 'Mexico',
  BR: 'Brasilien',
  AR: 'Argentina',
  CL: 'Chile',
  PE: 'Peru',
};
