/** 德语（de）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameDe = {
  English: 'Englisch',
  Arabic: 'Arabisch',
  Bengali: 'Bengalisch',
  Bosnian: 'Bosnisch',
  Bulgarian: 'Bulgarisch',
  Chinese: 'Chinesisch',
  Croatian: 'Kroatisch',
  Czech: 'Tschechisch',
  Danish: 'Dänisch',
  Dutch: 'Niederländisch',
  Estonian: 'Estnisch',
  Filipino: 'Filipino',
  Finnish: 'Finnisch',
  French: 'Französisch',
  German: 'Deutsch',
  Greek: 'Griechisch',
  Hebrew: 'Hebräisch',
  Hindi: 'Hindi',
  Hungarian: 'Ungarisch',
  Indonesian: 'Indonesisch',
  Irish: 'Irisch',
  Italian: 'Italienisch',
  Japanese: 'Japanisch',
  Korean: 'Koreanisch',
  Norwegian: 'Norwegisch',
  Polish: 'Polnisch',
  Portuguese: 'Portugiesisch',
  Romanian: 'Rumänisch',
  Russian: 'Russisch',
  Serbian: 'Serbisch',
  Slovak: 'Slowakisch',
  Slovenian: 'Slowenisch',
  Spanish: 'Spanisch',
  Swedish: 'Schwedisch',
  Thai: 'Thailändisch',
  Turkish: 'Türkisch',
  Ukrainian: 'Ukrainisch',
  Vietnamese: 'Vietnamesisch',
};

export const countryNamesDe = {
  US: 'Vereinigte Staaten',
  GB: 'Vereinigtes Königreich',
  AU: 'Australien',
  CA: 'Kanada',
  ZA: 'Südafrika',
  AE: 'Vereinigte Arabische Emirate',
  IN: 'Indien',
  DE: 'Deutschland',
  FR: 'Frankreich',
  ES: 'Spanien',
  IT: 'Italien',
  PT: 'Portugal',
  PL: 'Polen',
  RU: 'Russland',
  NL: 'Niederlande',
  TR: 'Türkei',
  CN: 'China',
  JP: 'Japan',
  KR: 'Südkorea',
  SE: 'Schweden',
  NO: 'Norwegen',
  DK: 'Dänemark',
  FI: 'Finnland',
  IL: 'Israel',
  AT: 'Österreich',
  CH: 'Schweiz',
  BE: 'Belgien',
  GR: 'Griechenland',
  IE: 'Irland',
  NZ: 'Neuseeland',
  SG: 'Singapur',
  HK: 'Hongkong',
  MX: 'Mexiko',
  BR: 'Brasilien',
  AR: 'Argentinien',
  CL: 'Chile',
  CO: 'Kolumbien',
  PE: 'Peru',
};
