/** 西班牙语（es）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameEs = {
  English: 'Inglés',
  Arabic: 'Árabe',
  Bengali: 'Bengalí',
  Bosnian: 'Bosnio',
  Bulgarian: 'Búlgaro',
  Chinese: 'Chino',
  Croatian: 'Croata',
  Czech: 'Checo',
  Danish: 'Danés',
  Dutch: 'Neerlandés',
  Estonian: 'Estonio',
  Filipino: 'Filipino',
  Finnish: 'Finlandés',
  French: 'Francés',
  German: 'Alemán',
  Greek: 'Griego',
  Hebrew: 'Hebreo',
  Hindi: 'Hindi',
  Hungarian: 'Húngaro',
  Indonesian: 'Indonesio',
  Irish: 'Irlandés',
  Italian: 'Italiano',
  Japanese: 'Japonés',
  Korean: 'Coreano',
  Norwegian: 'Noruego',
  Polish: 'Polaco',
  Portuguese: 'Portugués',
  Romanian: 'Rumano',
  Russian: 'Ruso',
  Serbian: 'Serbio',
  Slovak: 'Eslovaco',
  Slovenian: 'Esloveno',
  Spanish: 'Español',
  Swedish: 'Sueco',
  Thai: 'Tailandés',
  Turkish: 'Turco',
  Ukrainian: 'Ucraniano',
  Vietnamese: 'Vietnamita',
};

export const countryNamesEs = {
  US: 'Estados Unidos',
  GB: 'Reino Unido',
  AU: 'Australia',
  CA: 'Canadá',
  ZA: 'Sudáfrica',
  AE: 'Emiratos Árabes Unidos',
  IN: 'India',
  ES: 'España',
  DE: 'Alemania',
  FR: 'Francia',
  IT: 'Italia',
  PT: 'Portugal',
  PL: 'Polonia',
  RU: 'Rusia',
  NL: 'Países Bajos',
  TR: 'Turquía',
  CN: 'China',
  JP: 'Japón',
  KR: 'Corea del Sur',
  SE: 'Suecia',
  NO: 'Noruega',
  DK: 'Dinamarca',
  FI: 'Finlandia',
  IL: 'Israel',
  AT: 'Austria',
  CH: 'Suiza',
  BE: 'Bélgica',
  GR: 'Grecia',
  IE: 'Irlanda',
  NZ: 'Nueva Zelanda',
  SG: 'Singapur',
  MX: 'México',
  BR: 'Brasil',
  AR: 'Argentina',
  CL: 'Chile',
  CO: 'Colombia',
  PE: 'Perú',
};
