/** 芬兰语（fi）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameFi = {
  English: 'Englanti',
  Arabic: 'Arabia',
  Chinese: 'Kiina',
  Danish: 'Tanska',
  Dutch: 'Hollanti',
  Finnish: 'Suomi',
  French: 'Ranska',
  German: 'Saksa',
  Greek: 'Kreikka',
  Hebrew: 'Hebra',
  Hindi: 'Hindi',
  Italian: 'Italia',
  Japanese: 'Japani',
  Korean: 'Korea',
  Norwegian: 'Norja',
  Polish: 'Puola',
  Portuguese: 'Portugali',
  Romanian: 'Romania',
  Russian: 'Venäjä',
  Spanish: 'Espanja',
  Swedish: 'Ruotsi',
  Thai: 'Thai',
  Turkish: 'Turkki',
  Ukrainian: 'Ukraina',
  Vietnamese: 'Vietnam',
};

export const countryNamesFi = {
  US: 'USA',
  GB: 'Iso-Britannia',
  AU: 'Australia',
  CA: 'Kanada',
  ZA: 'Etelä-Afrikka',
  IN: 'Intia',
  DE: 'Saksa',
  FR: 'Ranska',
  ES: 'Espanja',
  IT: 'Italia',
  PT: 'Portugali',
  PL: 'Puola',
  RU: 'Venäjä',
  NL: 'Alankomaat',
  TR: 'Turkki',
  CN: 'Kiina',
  JP: 'Japani',
  KR: 'Etelä-Korea',
  SE: 'Ruotsi',
  NO: 'Norja',
  DK: 'Tanska',
  FI: 'Suomi',
  IL: 'Israel',
  AT: 'Itävalta',
  CH: 'Sveitsi',
  BE: 'Belgia',
  IE: 'Irlanti',
  NZ: 'Uusi-Seelanti',
  SG: 'Singapore',
  MX: 'Meksiko',
  BR: 'Brasilia',
  AR: 'Argentiina',
  CL: 'Chile',
  PE: 'Peru',
};
