/** 法语（fr）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameFr = {
  English: 'Anglais',
  Arabic: 'Arabe',
  Bengali: 'Bengali',
  Bosnian: 'Bosniaque',
  Bulgarian: 'Bulgare',
  Chinese: 'Chinois',
  Croatian: 'Croate',
  Czech: 'Tchèque',
  Danish: 'Danois',
  Dutch: 'Néerlandais',
  Estonian: 'Estonien',
  Filipino: 'Filipino',
  Finnish: 'Finnois',
  French: 'Français',
  German: 'Allemand',
  Greek: 'Grec',
  Hebrew: 'Hébreu',
  Hindi: 'Hindi',
  Hungarian: 'Hongrois',
  Indonesian: 'Indonésien',
  Irish: 'Irlandais',
  Italian: 'Italien',
  Japanese: 'Japonais',
  Korean: 'Coréen',
  Norwegian: 'Norvégien',
  Polish: 'Polonais',
  Portuguese: 'Portugais',
  Romanian: 'Roumain',
  Russian: 'Russe',
  Serbian: 'Serbe',
  Slovak: 'Slovaque',
  Slovenian: 'Slovène',
  Spanish: 'Espagnol',
  Swedish: 'Suédois',
  Thai: 'Thaï',
  Turkish: 'Turc',
  Ukrainian: 'Ukrainien',
  Vietnamese: 'Vietnamien',
};

export const countryNamesFr = {
  US: 'États-Unis',
  GB: 'Royaume-Uni',
  AU: 'Australie',
  CA: 'Canada',
  ZA: 'Afrique du Sud',
  AE: 'Émirats arabes unis',
  IN: 'Inde',
  FR: 'France',
  DE: 'Allemagne',
  ES: 'Espagne',
  IT: 'Italie',
  PT: 'Portugal',
  PL: 'Pologne',
  RU: 'Russie',
  NL: 'Pays-Bas',
  TR: 'Turquie',
  CN: 'Chine',
  JP: 'Japon',
  KR: 'Corée du Sud',
  SE: 'Suède',
  NO: 'Norvège',
  DK: 'Danemark',
  FI: 'Finlande',
  IL: 'Israël',
  AT: 'Autriche',
  CH: 'Suisse',
  BE: 'Belgique',
  GR: 'Grèce',
  IE: 'Irlande',
  NZ: 'Nouvelle-Zélande',
  SG: 'Singapour',
  MX: 'Mexique',
  BR: 'Brésil',
  AR: 'Argentine',
  CL: 'Chili',
  CO: 'Colombie',
  PE: 'Pérou',
};
