/** 印地语（hi）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameHi = {
  English: 'अंग्रेज़ी',
  Arabic: 'अरबी',
  Chinese: 'चीनी',
  French: 'फ्रेंच',
  German: 'जर्मन',
  Greek: 'यूनानी',
  Hebrew: 'हिब्रू',
  Hindi: 'हिंदी',
  Indonesian: 'इंडोनेशियाई',
  Italian: 'इतालवी',
  Japanese: 'जापानी',
  Korean: 'कोरियाई',
  Portuguese: 'पुर्तगाली',
  Russian: 'रूसी',
  Spanish: 'स्पेनिश',
  Thai: 'थाई',
  Turkish: 'तुर्की',
  Ukrainian: 'यूक्रेनियाई',
  Vietnamese: 'वियतनामी',
};

export const countryNamesHi = {
  US: 'अमेरिका',
  GB: 'ब्रिटेन',
  AU: 'ऑस्ट्रेलिया',
  CA: 'कनाडा',
  IN: 'भारत',
  DE: 'जर्मनी',
  FR: 'फ्रांस',
  ES: 'स्पेन',
  IT: 'इटली',
  PT: 'पुर्तगाल',
  PL: 'पोलैंड',
  RU: 'रूस',
  NL: 'नीदरलैंड',
  TR: 'तुर्की',
  CN: 'चीन',
  JP: 'जापान',
  KR: 'दक्षिण कोरिया',
  SE: 'स्वीडन',
  NO: 'नॉर्वे',
  DK: 'डेनमार्क',
  FI: 'फिनलैंड',
  IL: 'इज़राइल',
  IE: 'आयरलैंड',
  NZ: 'न्यूजीलैंड',
  SG: 'सिंगापुर',
  MX: 'मेक्सिको',
  BR: 'ब्राजील',
  AR: 'अर्जेंटीना',
  PH: 'फिलीपींस',
};
