/** 意大利语（it）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameIt = {
  English: 'Inglese',
  Arabic: 'Arabo',
  Bengali: 'Bengalese',
  Bosnian: 'Bosniaco',
  Bulgarian: 'Bulgaro',
  Chinese: 'Cinese',
  Croatian: 'Croato',
  Czech: 'Ceco',
  Danish: 'Danese',
  Dutch: 'Olandese',
  Estonian: 'Estone',
  Filipino: 'Filipino',
  Finnish: 'Finlandese',
  French: 'Francese',
  German: 'Tedesco',
  Greek: 'Greco',
  Hebrew: 'Ebraico',
  Hindi: 'Hindi',
  Hungarian: 'Ungherese',
  Indonesian: 'Indonesiano',
  Irish: 'Irlandese',
  Italian: 'Italiano',
  Japanese: 'Giapponese',
  Korean: 'Coreano',
  Norwegian: 'Norvegese',
  Polish: 'Polacco',
  Portuguese: 'Portoghese',
  Romanian: 'Rumeno',
  Russian: 'Russo',
  Serbian: 'Serbo',
  Slovak: 'Slovacco',
  Slovenian: 'Sloveno',
  Spanish: 'Spagnolo',
  Swedish: 'Svedese',
  Thai: 'Tailandese',
  Turkish: 'Turco',
  Ukrainian: 'Ucraino',
  Vietnamese: 'Vietnamita',
};

export const countryNamesIt = {
  US: 'Stati Uniti',
  GB: 'Regno Unito',
  AU: 'Australia',
  CA: 'Canada',
  ZA: 'Sudafrica',
  AE: 'Emirati Arabi Uniti',
  IN: 'India',
  IT: 'Italia',
  DE: 'Germania',
  FR: 'Francia',
  ES: 'Spagna',
  PT: 'Portogallo',
  PL: 'Polonia',
  RU: 'Russia',
  NL: 'Paesi Bassi',
  TR: 'Turchia',
  CN: 'Cina',
  JP: 'Giappone',
  KR: 'Corea del Sud',
  SE: 'Svezia',
  NO: 'Norvegia',
  DK: 'Danimarca',
  FI: 'Finlandia',
  IL: 'Israele',
  AT: 'Austria',
  CH: 'Svizzera',
  BE: 'Belgio',
  GR: 'Grecia',
  IE: 'Irlanda',
  NZ: 'Nuova Zelanda',
  SG: 'Singapore',
  MX: 'Messico',
  BR: 'Brasile',
  AR: 'Argentina',
  CL: 'Cile',
  CO: 'Colombia',
  PE: 'Perù',
};
