/** 日语（ja）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameJa = {
  English: '英語',
  Arabic: 'アラビア語',
  Bengali: 'ベンガル語',
  Chinese: '中国語',
  Danish: 'デンマーク語',
  Dutch: 'オランダ語',
  Finnish: 'フィンランド語',
  French: 'フランス語',
  German: 'ドイツ語',
  Greek: 'ギリシャ語',
  Hebrew: 'ヘブライ語',
  Hindi: 'ヒンディー語',
  Indonesian: 'インドネシア語',
  Italian: 'イタリア語',
  Japanese: '日本語',
  Korean: '韓国語',
  Norwegian: 'ノルウェー語',
  Polish: 'ポーランド語',
  Portuguese: 'ポルトガル語',
  Romanian: 'ルーマニア語',
  Russian: 'ロシア語',
  Spanish: 'スペイン語',
  Swedish: 'スウェーデン語',
  Thai: 'タイ語',
  Turkish: 'トルコ語',
  Ukrainian: 'ウクライナ語',
  Vietnamese: 'ベトナム語',
};

export const countryNamesJa = {
  US: 'アメリカ',
  GB: 'イギリス',
  AU: 'オーストラリア',
  CA: 'カナダ',
  ZA: '南アフリカ',
  AE: 'UAE',
  IN: 'インド',
  DE: 'ドイツ',
  FR: 'フランス',
  ES: 'スペイン',
  IT: 'イタリア',
  PT: 'ポルトガル',
  PL: 'ポーランド',
  RU: 'ロシア',
  NL: 'オランダ',
  TR: 'トルコ',
  CN: '中国',
  JP: '日本',
  KR: '韓国',
  SE: 'スウェーデン',
  NO: 'ノルウェー',
  DK: 'デンマーク',
  FI: 'フィンランド',
  IL: 'イスラエル',
  AT: 'オーストリア',
  CH: 'スイス',
  BE: 'ベルギー',
  GR: 'ギリシャ',
  IE: 'アイルランド',
  NZ: 'ニュージーランド',
  SG: 'シンガポール',
  MX: 'メキシコ',
  BR: 'ブラジル',
  AR: 'アルゼンチン',
  CL: 'チリ',
  CO: 'コロンビア',
  PE: 'ペルー',
  PH: 'フィリピン',
  HK: '香港',
  TW: '台湾',
};
