/** 韩语（ko）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameKo = {
  English: '영어',
  Arabic: '아랍어',
  Chinese: '중국어',
  Danish: '덴마크어',
  Dutch: '네덜란드어',
  Finnish: '핀란드어',
  French: '프랑스어',
  German: '독일어',
  Greek: '그리스어',
  Hebrew: '히브리어',
  Hindi: '힌디어',
  Indonesian: '인도네시아어',
  Italian: '이탈리아어',
  Japanese: '일본어',
  Korean: '한국어',
  Norwegian: '노르웨이어',
  Polish: '폴란드어',
  Portuguese: '포르투갈어',
  Romanian: '루마니아어',
  Russian: '러시아어',
  Spanish: '스페인어',
  Swedish: '스웨덴어',
  Thai: '태국어',
  Turkish: '터키어',
  Ukrainian: '우크라이나어',
  Vietnamese: '베트남어',
};

export const countryNamesKo = {
  US: '미국',
  GB: '영국',
  AU: '호주',
  CA: '캐나다',
  ZA: '남아프리카',
  AE: 'UAE',
  IN: '인도',
  DE: '독일',
  FR: '프랑스',
  ES: '스페인',
  IT: '이탈리아',
  PT: '포르투갈',
  PL: '폴란드',
  RU: '러시아',
  NL: '네덜란드',
  TR: '터키',
  CN: '중국',
  JP: '일본',
  KR: '대한민국',
  SE: '스웨덴',
  NO: '노르웨이',
  DK: '덴마크',
  FI: '핀란드',
  IL: '이스라엘',
  AT: '오스트리아',
  CH: '스위스',
  BE: '벨기에',
  GR: '그리스',
  IE: '아일랜드',
  NZ: '뉴질랜드',
  SG: '싱가포르',
  MX: '멕시코',
  BR: '브라질',
  AR: '아르헨티나',
  CL: '칠레',
  CO: '콜롬비아',
  PE: '페루',
  PH: '필리핀',
  HK: '홍콩',
  TW: '대만',
};
