/** 荷兰语（nl）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameNl = {
  English: 'Engels',
  Arabic: 'Arabisch',
  Bengali: 'Bengalees',
  Bosnian: 'Bosnisch',
  Bulgarian: 'Bulgaars',
  Chinese: 'Chinees',
  Croatian: 'Kroatisch',
  Czech: 'Tsjechisch',
  Danish: 'Deens',
  Dutch: 'Nederlands',
  Estonian: 'Estisch',
  Filipino: 'Filipijns',
  Finnish: 'Fins',
  French: 'Frans',
  German: 'Duits',
  Greek: 'Grieks',
  Hebrew: 'Hebreeuws',
  Hindi: 'Hindi',
  Hungarian: 'Hongaars',
  Indonesian: 'Indonesisch',
  Irish: 'Iers',
  Italian: 'Italiaans',
  Japanese: 'Japans',
  Korean: 'Koreaans',
  Norwegian: 'Noors',
  Polish: 'Pools',
  Portuguese: 'Portugees',
  Romanian: 'Roemeens',
  Russian: 'Russisch',
  Serbian: 'Servisch',
  Slovak: 'Slovaaks',
  Slovenian: 'Sloveens',
  Spanish: 'Spaans',
  Swedish: 'Zweeds',
  Thai: 'Thai',
  Turkish: 'Turks',
  Ukrainian: 'Oekraïens',
  Vietnamese: 'Vietnamees',
};

export const countryNamesNl = {
  US: 'Verenigde Staten',
  GB: 'Verenigd Koninkrijk',
  AU: 'Australië',
  CA: 'Canada',
  ZA: 'Zuid-Afrika',
  AE: 'Verenigde Arabische Emiraten',
  IN: 'India',
  DE: 'Duitsland',
  FR: 'Frankrijk',
  ES: 'Spanje',
  IT: 'Italië',
  PT: 'Portugal',
  PL: 'Polen',
  RU: 'Rusland',
  NL: 'Nederland',
  TR: 'Turkije',
  CN: 'China',
  JP: 'Japan',
  KR: 'Zuid-Korea',
  SE: 'Zweden',
  NO: 'Noorwegen',
  DK: 'Denemarken',
  FI: 'Finland',
  IL: 'Israël',
  AT: 'Oostenrijk',
  CH: 'Zwitserland',
  BE: 'België',
  GR: 'Griekenland',
  IE: 'Ierland',
  NZ: 'Nieuw-Zeeland',
  SG: 'Singapore',
  MX: 'Mexico',
  BR: 'Brazilië',
  AR: 'Argentinië',
  CL: 'Chili',
  CO: 'Colombia',
  PE: 'Peru',
};
