/** 挪威语（no）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameNo = {
  English: 'Engelsk',
  Arabic: 'Arabisk',
  Chinese: 'Kinesisk',
  Danish: 'Dansk',
  Dutch: 'Nederlandsk',
  Finnish: 'Finsk',
  French: 'Fransk',
  German: 'Tysk',
  Greek: 'Gresk',
  Hebrew: 'Hebraisk',
  Hindi: 'Hindi',
  Italian: 'Italiensk',
  Japanese: 'Japansk',
  Korean: 'Koreansk',
  Norwegian: 'Norsk',
  Polish: 'Polsk',
  Portuguese: 'Portugisisk',
  Romanian: 'Rumensk',
  Russian: 'Russisk',
  Spanish: 'Spansk',
  Swedish: 'Svensk',
  Thai: 'Thai',
  Turkish: 'Tyrkisk',
  Ukrainian: 'Ukrainsk',
  Vietnamese: 'Vietnamesisk',
};

export const countryNamesNo = {
  US: 'USA',
  GB: 'Storbritannia',
  AU: 'Australia',
  CA: 'Canada',
  ZA: 'Sør-Afrika',
  IN: 'India',
  DE: 'Tyskland',
  FR: 'Frankrike',
  ES: 'Spania',
  IT: 'Italia',
  PT: 'Portugal',
  PL: 'Polen',
  RU: 'Russland',
  NL: 'Nederland',
  TR: 'Tyrkia',
  CN: 'Kina',
  JP: 'Japan',
  KR: 'Sør-Korea',
  SE: 'Sverige',
  NO: 'Norge',
  DK: 'Danmark',
  FI: 'Finland',
  IL: 'Israel',
  AT: 'Østerrike',
  CH: 'Sveits',
  BE: 'Belgia',
  IE: 'Irland',
  NZ: 'New Zealand',
  SG: 'Singapore',
  MX: 'Mexico',
  BR: 'Brasil',
  AR: 'Argentina',
  CL: 'Chile',
  PE: 'Peru',
};
