/** 波兰语（pl）的界面显示名翻译表：语言名 + 国家名 */

export const languageNamePl = {
  English: 'Angielski',
  Arabic: 'Arabski',
  Bengali: 'Bengalski',
  Bosnian: 'Bośniacki',
  Bulgarian: 'Bułgarski',
  Chinese: 'Chiński',
  Croatian: 'Chorwacki',
  Czech: 'Czeski',
  Danish: 'Duński',
  Dutch: 'Niderlandzki',
  Estonian: 'Estoński',
  Filipino: 'Filipino',
  Finnish: 'Fiński',
  French: 'Francuski',
  German: 'Niemiecki',
  Greek: 'Grecki',
  Hebrew: 'Hebrajski',
  Hindi: 'Hindi',
  Hungarian: 'Węgierski',
  Indonesian: 'Indonezyjski',
  Irish: 'Irlandzki',
  Italian: 'Włoski',
  Japanese: 'Japoński',
  Korean: 'Koreański',
  Norwegian: 'Norweski',
  Polish: 'Polski',
  Portuguese: 'Portugalski',
  Romanian: 'Rumuński',
  Russian: 'Rosyjski',
  Serbian: 'Serbski',
  Slovak: 'Słowacki',
  Slovenian: 'Słoweński',
  Spanish: 'Hiszpański',
  Swedish: 'Szwedzki',
  Thai: 'Tajski',
  Turkish: 'Turecki',
  Ukrainian: 'Ukraiński',
  Vietnamese: 'Wietnamski',
};

export const countryNamesPl = {
  US: 'Stany Zjednoczone',
  GB: 'Wielka Brytania',
  AU: 'Australia',
  CA: 'Kanada',
  ZA: 'Republika Południowej Afryki',
  IN: 'Indie',
  DE: 'Niemcy',
  FR: 'Francja',
  ES: 'Hiszpania',
  IT: 'Włochy',
  PT: 'Portugalia',
  PL: 'Polska',
  RU: 'Rosja',
  NL: 'Holandia',
  TR: 'Turcja',
  CN: 'Chiny',
  JP: 'Japonia',
  KR: 'Korea Południowa',
  SE: 'Szwecja',
  NO: 'Norwegia',
  DK: 'Dania',
  FI: 'Finlandia',
  IL: 'Izrael',
  AT: 'Austria',
  CH: 'Szwajcaria',
  BE: 'Belgia',
  GR: 'Grecja',
  IE: 'Irlandia',
  NZ: 'Nowa Zelandia',
  SG: 'Singapur',
  MX: 'Meksyk',
  BR: 'Brazylia',
  AR: 'Argentyna',
  CL: 'Chile',
  CO: 'Kolumbia',
  PE: 'Peru',
};
