/** 葡萄牙语（pt）的界面显示名翻译表：语言名 + 国家名 */

export const languageNamePt = {
  English: 'Inglês',
  Arabic: 'Árabe',
  Bengali: 'Bengali',
  Bosnian: 'Bósnio',
  Bulgarian: 'Búlgaro',
  Chinese: 'Chinês',
  Croatian: 'Croata',
  Czech: 'Checo',
  Danish: 'Dinamarquês',
  Dutch: 'Holandês',
  Estonian: 'Estoniano',
  Filipino: 'Filipino',
  Finnish: 'Finlandês',
  French: 'Francês',
  German: 'Alemão',
  Greek: 'Grego',
  Hebrew: 'Hebraico',
  Hindi: 'Hindi',
  Hungarian: 'Húngaro',
  Indonesian: 'Indonésio',
  Irish: 'Irlandês',
  Italian: 'Italiano',
  Japanese: 'Japonês',
  Korean: 'Coreano',
  Norwegian: 'Norueguês',
  Polish: 'Polonês',
  Portuguese: 'Português',
  Romanian: 'Romeno',
  Russian: 'Russo',
  Serbian: 'Sérvio',
  Slovak: 'Eslovaco',
  Slovenian: 'Esloveno',
  Spanish: 'Espanhol',
  Swedish: 'Sueco',
  Thai: 'Tailandês',
  Turkish: 'Turco',
  Ukrainian: 'Ucraniano',
  Vietnamese: 'Vietnamita',
};

export const countryNamesPt = {
  US: 'Estados Unidos',
  GB: 'Reino Unido',
  AU: 'Austrália',
  CA: 'Canadá',
  ZA: 'África do Sul',
  AE: 'Emirados Árabes Unidos',
  IN: 'Índia',
  PT: 'Portugal',
  DE: 'Alemanha',
  FR: 'França',
  ES: 'Espanha',
  IT: 'Itália',
  PL: 'Polônia',
  RU: 'Rússia',
  NL: 'Países Baixos',
  TR: 'Turquia',
  CN: 'China',
  JP: 'Japão',
  KR: 'Coreia do Sul',
  SE: 'Suécia',
  NO: 'Noruega',
  DK: 'Dinamarca',
  FI: 'Finlândia',
  IL: 'Israel',
  AT: 'Áustria',
  CH: 'Suíça',
  BE: 'Bélgica',
  GR: 'Grécia',
  IE: 'Irlanda',
  NZ: 'Nova Zelândia',
  SG: 'Singapura',
  MX: 'México',
  BR: 'Brasil',
  AR: 'Argentina',
  CL: 'Chile',
  CO: 'Colômbia',
  PE: 'Peru',
};
