/** 瑞典语（sv）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameSv = {
  English: 'Engelska',
  Arabic: 'Arabiska',
  Chinese: 'Kinesiska',
  Danish: 'Danska',
  Dutch: 'Nederländska',
  Finnish: 'Finska',
  French: 'Franska',
  German: 'Tyska',
  Greek: 'Grekiska',
  Hebrew: 'Hebreiska',
  Hindi: 'Hindi',
  Italian: 'Italienska',
  Japanese: 'Japanska',
  Korean: 'Koreanska',
  Norwegian: 'Norska',
  Polish: 'Polska',
  Portuguese: 'Portugisiska',
  Romanian: 'Rumänska',
  Russian: 'Ryska',
  Spanish: 'Spanska',
  Swedish: 'Svenska',
  Thai: 'Thailändska',
  Turkish: 'Turkiska',
  Ukrainian: 'Ukrainska',
  Vietnamese: 'Vietnamesiska',
};

export const countryNamesSv = {
  US: 'USA',
  GB: 'Storbritannien',
  AU: 'Australien',
  CA: 'Kanada',
  ZA: 'Sydafrika',
  IN: 'Indien',
  DE: 'Tyskland',
  FR: 'Frankrike',
  ES: 'Spanien',
  IT: 'Italien',
  PT: 'Portugal',
  PL: 'Polen',
  RU: 'Ryssland',
  NL: 'Nederländerna',
  TR: 'Turkiet',
  CN: 'Kina',
  JP: 'Japan',
  KR: 'Sydkorea',
  SE: 'Sverige',
  NO: 'Norge',
  DK: 'Danmark',
  FI: 'Finland',
  IL: 'Israel',
  AT: 'Österrike',
  CH: 'Schweiz',
  BE: 'Belgien',
  IE: 'Irland',
  NZ: 'Nya Zeeland',
  SG: 'Singapore',
  MX: 'Mexiko',
  BR: 'Brasilien',
  AR: 'Argentina',
  CL: 'Chile',
  PE: 'Peru',
};
