/** 土耳其语（tr）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameTr = {
  English: 'İngilizce',
  Arabic: 'Arapça',
  Bengali: 'Bengalce',
  Bosnian: 'Boşnakça',
  Bulgarian: 'Bulgarca',
  Chinese: 'Çince',
  Croatian: 'Hırvatça',
  Czech: 'Çekçe',
  Danish: 'Danca',
  Dutch: 'Felemenkçe',
  Estonian: 'Estçe',
  Filipino: 'Filipince',
  Finnish: 'Fince',
  French: 'Fransızca',
  German: 'Almanca',
  Greek: 'Yunanca',
  Hebrew: 'İbranice',
  Hindi: 'Hintçe',
  Hungarian: 'Macarca',
  Indonesian: 'Endonezce',
  Irish: 'İrlandaca',
  Italian: 'İtalyanca',
  Japanese: 'Japonca',
  Korean: 'Korece',
  Norwegian: 'Norveççe',
  Polish: 'Lehçe',
  Portuguese: 'Portekizce',
  Romanian: 'Rumence',
  Russian: 'Rusça',
  Serbian: 'Sırpça',
  Slovak: 'Slovakça',
  Slovenian: 'Slovence',
  Spanish: 'İspanyolca',
  Swedish: 'İsveççe',
  Thai: 'Tayca',
  Turkish: 'Türkçe',
  Ukrainian: 'Ukraynaca',
  Vietnamese: 'Vietnamca',
};

export const countryNamesTr = {
  US: 'ABD',
  GB: 'Birleşik Krallık',
  AU: 'Avustralya',
  CA: 'Kanada',
  ZA: 'Güney Afrika',
  AE: 'BAE',
  IN: 'Hindistan',
  DE: 'Almanya',
  FR: 'Fransa',
  ES: 'İspanya',
  IT: 'İtalya',
  PT: 'Portekiz',
  PL: 'Polonya',
  RU: 'Rusya',
  NL: 'Hollanda',
  TR: 'Türkiye',
  CN: 'Çin',
  JP: 'Japonya',
  KR: 'Güney Kore',
  SE: 'İsveç',
  NO: 'Norveç',
  DK: 'Danimarka',
  FI: 'Finlandiya',
  IL: 'İsrail',
  AT: 'Avusturya',
  CH: 'İsviçre',
  BE: 'Belçika',
  GR: 'Yunanistan',
  IE: 'İrlanda',
  NZ: 'Yeni Zelanda',
  SG: 'Singapur',
  MX: 'Meksika',
  BR: 'Brezilya',
  AR: 'Arjantin',
  CL: 'Şili',
  CO: 'Kolombiya',
  PE: 'Peru',
};
