/** 中文（zh）的界面显示名翻译表：语言名 + 国家名 */

export const languageNameZh = {
  English: '英语',
  Arabic: '阿拉伯语',
  Chinese: '中文',
  Danish: '丹麦语',
  Dutch: '荷兰语',
  Finnish: '芬兰语',
  French: '法语',
  German: '德语',
  Greek: '希腊语',
  Hebrew: '希伯来语',
  Hindi: '印地语',
  Indonesian: '印尼语',
  Italian: '意大利语',
  Japanese: '日语',
  Korean: '韩语',
  Norwegian: '挪威语',
  Polish: '波兰语',
  Portuguese: '葡萄牙语',
  Romanian: '罗马尼亚语',
  Russian: '俄语',
  Spanish: '西班牙语',
  Swedish: '瑞典语',
  Thai: '泰语',
  Turkish: '土耳其语',
  Ukrainian: '乌克兰语',
  Vietnamese: '越南语',
};

export const countryNamesZh = {
  US: '美国',
  GB: '英国',
  AU: '澳大利亚',
  CA: '加拿大',
  ZA: '南非',
  AE: '阿联酋',
  IN: '印度',
  DE: '德国',
  FR: '法国',
  ES: '西班牙',
  IT: '意大利',
  PT: '葡萄牙',
  PL: '波兰',
  RU: '俄罗斯',
  NL: '荷兰',
  TR: '土耳其',
  CN: '中国',
  JP: '日本',
  KR: '韩国',
  SE: '瑞典',
  NO: '挪威',
  DK: '丹麦',
  FI: '芬兰',
  IL: '以色列',
  AT: '奥地利',
  CH: '瑞士',
  BE: '比利时',
  GR: '希腊',
  IE: '爱尔兰',
  NZ: '新西兰',
  SG: '新加坡',
  MX: '墨西哥',
  BR: '巴西',
  AR: '阿根廷',
  CL: '智利',
  CO: '哥伦比亚',
  PE: '秘鲁',
  PH: '菲律宾',
  HK: '香港',
  TW: '台湾',
};
