/** Language / country / gender name translation tables. */
export const languageNames = {
  'af-ZA': 'Afrikaans',
  'sq-AL': 'Albanian',
  'am-ET': 'Amharic',
  ar: 'Arabic',
  'az-AZ': 'Azerbaijani',
  bn: 'Bengali',
  'bs-BA': 'Bosnian',
  'bg-BG': 'Bulgarian',
  'my-MM': 'Burmese',
  'ca-ES': 'Catalan',
  zh: 'Chinese',
  'hr-HR': 'Croatian',
  'cs-CZ': 'Czech',
  'da-DK': 'Danish',
  nl: 'Dutch',
  en: 'English',
  'et-EE': 'Estonian',
  'fil-PH': 'Filipino',
  'fi-FI': 'Finnish',
  fr: 'French',
  'gl-ES': 'Galician',
  'ka-GE': 'Georgian',
  de: 'German',
  'el-GR': 'Greek',
  'gu-IN': 'Gujarati',
  'he-IL': 'Hebrew',
  'hi-IN': 'Hindi',
  'hu-HU': 'Hungarian',
  'is-IS': 'Icelandic',
  'id-ID': 'Indonesian',
  iu: 'Inuktitut',
  'ga-IE': 'Irish',
  'it-IT': 'Italian',
  'ja-JP': 'Japanese',
  'jv-ID': 'Javanese',
  'kn-IN': 'Kannada',
  'kk-KZ': 'Kazakh',
  'km-KH': 'Khmer',
  'ko-KR': 'Korean',
  'lo-LA': 'Lao',
  'lv-LV': 'Latvian',
  'lt-LT': 'Lithuanian',
  'mk-MK': 'Macedonian',
  'ms-MY': 'Malay',
  'ml-IN': 'Malayalam',
  'mt-MT': 'Maltese',
  'mr-IN': 'Marathi',
  'mn-MN': 'Mongolian',
  'ne-NP': 'Nepali',
  'nb-NO': 'Norwegian',
  'ps-AF': 'Pashto',
  'fa-IR': 'Persian',
  'pl-PL': 'Polish',
  pt: 'Portuguese',
  'ro-RO': 'Romanian',
  'ru-RU': 'Russian',
  'sr-RS': 'Serbian',
  'si-LK': 'Sinhala',
  'sk-SK': 'Slovak',
  'sl-SI': 'Slovenian',
  'so-SO': 'Somali',
  es: 'Spanish',
  'su-ID': 'Sundanese',
  sw: 'Swahili',
  'sv-SE': 'Swedish',
  ta: 'Tamil',
  'te-IN': 'Telugu',
  'th-TH': 'Thai',
  'tr-TR': 'Turkish',
  'uk-UA': 'Ukrainian',
  ur: 'Urdu',
  'uz-UZ': 'Uzbek',
  'vi-VN': 'Vietnamese',
  'cy-GB': 'Welsh',
  'zu-ZA': 'Zulu',
};

// Language name translations by interface locale (English -> translated)
const languageNameRu = {
  English: 'Английский',
  Arabic: 'Арабский',
  Bengali: 'Бенгальский',
  Bosnian: 'Боснийский',
  Bulgarian: 'Болгарский',
  Chinese: 'Китайский',
  Croatian: 'Хорватский',
  Czech: 'Чешский',
  Danish: 'Датский',
  Dutch: 'Голландский',
  Estonian: 'Эстонский',
  Filipino: 'Филиппинский',
  Finnish: 'Финский',
  French: 'Французский',
  German: 'Немецкий',
  Greek: 'Греческий',
  Hebrew: 'Иврит',
  Hindi: 'Хинди',
  Hungarian: 'Венгерский',
  Indonesian: 'Индонезийский',
  Irish: 'Ирландский',
  Italian: 'Итальянский',
  Japanese: 'Японский',
  Korean: 'Корейский',
  Norwegian: 'Норвежский',
  Polish: 'Польский',
  Portuguese: 'Португальский',
  Romanian: 'Румынский',
  Russian: 'Русский',
  Serbian: 'Сербский',
  Slovak: 'Словацкий',
  Slovenian: 'Словенский',
  Spanish: 'Испанский',
  Swedish: 'Шведский',
  Thai: 'Тайский',
  Turkish: 'Турецкий',
  Ukrainian: 'Украинский',
  Vietnamese: 'Вьетнамский',
  Afrikaans: 'Африкаанс',
  Albanian: 'Албанский',
  Amharic: 'Амхарский',
  Azerbaijani: 'Азербайджанский',
  Burmese: 'Бирманский',
  Catalan: 'Каталанский',
  Galician: 'Галисийский',
  Georgian: 'Грузинский',
  Gujarati: 'Гуджарати',
  Icelandic: 'Исландский',
  Kannada: 'Каннада',
  Kazakh: 'Казахский',
  Khmer: 'Кхмерский',
  Lao: 'Лаосский',
  Latvian: 'Латышский',
  Lithuanian: 'Литовский',
  Macedonian: 'Македонский',
  Malay: 'Малайский',
  Malayalam: 'Малаялам',
  Maltese: 'Мальтийский',
  Marathi: 'Маратхи',
  Mongolian: 'Монгольский',
  Nepali: 'Непальский',
  Pashto: 'Пушту',
  Persian: 'Персидский',
  Sinhala: 'Сингальский',
  Somali: 'Сомали',
  Swahili: 'Суахили',
  Tamil: 'Тамильский',
  Telugu: 'Телугу',
  Urdu: 'Урду',
  Uzbek: 'Узбекский',
  Welsh: 'Валлийский',
  Zulu: 'Зулу',
  Inuktitut: 'Инуктитут',
  Javanese: 'Яванский',
  Sundanese: 'Сунданский',
};
const languageNameDe = {
  English: 'Englisch',
  Arabic: 'Arabisch',
  Bengali: 'Bengalisch',
  Bosnian: 'Bosnisch',
  Bulgarian: 'Bulgarisch',
  Chinese: 'Chinesisch',
  Croatian: 'Kroatisch',
  Czech: 'Tschechisch',
  Danish: 'Dänisch',
  Dutch: 'Niederländisch',
  Estonian: 'Estnisch',
  Filipino: 'Filipino',
  Finnish: 'Finnisch',
  French: 'Französisch',
  German: 'Deutsch',
  Greek: 'Griechisch',
  Hebrew: 'Hebräisch',
  Hindi: 'Hindi',
  Hungarian: 'Ungarisch',
  Indonesian: 'Indonesisch',
  Irish: 'Irisch',
  Italian: 'Italienisch',
  Japanese: 'Japanisch',
  Korean: 'Koreanisch',
  Norwegian: 'Norwegisch',
  Polish: 'Polnisch',
  Portuguese: 'Portugiesisch',
  Romanian: 'Rumänisch',
  Russian: 'Russisch',
  Serbian: 'Serbisch',
  Slovak: 'Slowakisch',
  Slovenian: 'Slowenisch',
  Spanish: 'Spanisch',
  Swedish: 'Schwedisch',
  Thai: 'Thailändisch',
  Turkish: 'Türkisch',
  Ukrainian: 'Ukrainisch',
  Vietnamese: 'Vietnamesisch',
};
const languageNameFr = {
  English: 'Anglais',
  Arabic: 'Arabe',
  Bengali: 'Bengali',
  Bosnian: 'Bosniaque',
  Bulgarian: 'Bulgare',
  Chinese: 'Chinois',
  Croatian: 'Croate',
  Czech: 'Tchèque',
  Danish: 'Danois',
  Dutch: 'Néerlandais',
  Estonian: 'Estonien',
  Filipino: 'Filipino',
  Finnish: 'Finnois',
  French: 'Français',
  German: 'Allemand',
  Greek: 'Grec',
  Hebrew: 'Hébreu',
  Hindi: 'Hindi',
  Hungarian: 'Hongrois',
  Indonesian: 'Indonésien',
  Irish: 'Irlandais',
  Italian: 'Italien',
  Japanese: 'Japonais',
  Korean: 'Coréen',
  Norwegian: 'Norvégien',
  Polish: 'Polonais',
  Portuguese: 'Portugais',
  Romanian: 'Roumain',
  Russian: 'Russe',
  Serbian: 'Serbe',
  Slovak: 'Slovaque',
  Slovenian: 'Slovène',
  Spanish: 'Espagnol',
  Swedish: 'Suédois',
  Thai: 'Thaï',
  Turkish: 'Turc',
  Ukrainian: 'Ukrainien',
  Vietnamese: 'Vietnamien',
};
const languageNameEs = {
  English: 'Inglés',
  Arabic: 'Árabe',
  Bengali: 'Bengalí',
  Bosnian: 'Bosnio',
  Bulgarian: 'Búlgaro',
  Chinese: 'Chino',
  Croatian: 'Croata',
  Czech: 'Checo',
  Danish: 'Danés',
  Dutch: 'Neerlandés',
  Estonian: 'Estonio',
  Filipino: 'Filipino',
  Finnish: 'Finlandés',
  French: 'Francés',
  German: 'Alemán',
  Greek: 'Griego',
  Hebrew: 'Hebreo',
  Hindi: 'Hindi',
  Hungarian: 'Húngaro',
  Indonesian: 'Indonesio',
  Irish: 'Irlandés',
  Italian: 'Italiano',
  Japanese: 'Japonés',
  Korean: 'Coreano',
  Norwegian: 'Noruego',
  Polish: 'Polaco',
  Portuguese: 'Portugués',
  Romanian: 'Rumano',
  Russian: 'Ruso',
  Serbian: 'Serbio',
  Slovak: 'Eslovaco',
  Slovenian: 'Esloveno',
  Spanish: 'Español',
  Swedish: 'Sueco',
  Thai: 'Tailandés',
  Turkish: 'Turco',
  Ukrainian: 'Ucraniano',
  Vietnamese: 'Vietnamita',
};
const languageNameIt = {
  English: 'Inglese',
  Arabic: 'Arabo',
  Bengali: 'Bengalese',
  Bosnian: 'Bosniaco',
  Bulgarian: 'Bulgaro',
  Chinese: 'Cinese',
  Croatian: 'Croato',
  Czech: 'Ceco',
  Danish: 'Danese',
  Dutch: 'Olandese',
  Estonian: 'Estone',
  Filipino: 'Filipino',
  Finnish: 'Finlandese',
  French: 'Francese',
  German: 'Tedesco',
  Greek: 'Greco',
  Hebrew: 'Ebraico',
  Hindi: 'Hindi',
  Hungarian: 'Ungherese',
  Indonesian: 'Indonesiano',
  Irish: 'Irlandese',
  Italian: 'Italiano',
  Japanese: 'Giapponese',
  Korean: 'Coreano',
  Norwegian: 'Norvegese',
  Polish: 'Polacco',
  Portuguese: 'Portoghese',
  Romanian: 'Rumeno',
  Russian: 'Russo',
  Serbian: 'Serbo',
  Slovak: 'Slovacco',
  Slovenian: 'Sloveno',
  Spanish: 'Spagnolo',
  Swedish: 'Svedese',
  Thai: 'Tailandese',
  Turkish: 'Turco',
  Ukrainian: 'Ucraino',
  Vietnamese: 'Vietnamita',
};
const languageNamePl = {
  English: 'Angielski',
  Arabic: 'Arabski',
  Bengali: 'Bengalski',
  Bosnian: 'Bośniacki',
  Bulgarian: 'Bułgarski',
  Chinese: 'Chiński',
  Croatian: 'Chorwacki',
  Czech: 'Czeski',
  Danish: 'Duński',
  Dutch: 'Niderlandzki',
  Estonian: 'Estoński',
  Filipino: 'Filipino',
  Finnish: 'Fiński',
  French: 'Francuski',
  German: 'Niemiecki',
  Greek: 'Grecki',
  Hebrew: 'Hebrajski',
  Hindi: 'Hindi',
  Hungarian: 'Węgierski',
  Indonesian: 'Indonezyjski',
  Irish: 'Irlandzki',
  Italian: 'Włoski',
  Japanese: 'Japoński',
  Korean: 'Koreański',
  Norwegian: 'Norweski',
  Polish: 'Polski',
  Portuguese: 'Portugalski',
  Romanian: 'Rumuński',
  Russian: 'Rosyjski',
  Serbian: 'Serbski',
  Slovak: 'Słowacki',
  Slovenian: 'Słoweński',
  Spanish: 'Hiszpański',
  Swedish: 'Szwedzki',
  Thai: 'Tajski',
  Turkish: 'Turecki',
  Ukrainian: 'Ukraiński',
  Vietnamese: 'Wietnamski',
};
const languageNamePt = {
  English: 'Inglês',
  Arabic: 'Árabe',
  Bengali: 'Bengali',
  Bosnian: 'Bósnio',
  Bulgarian: 'Búlgaro',
  Chinese: 'Chinês',
  Croatian: 'Croata',
  Czech: 'Checo',
  Danish: 'Dinamarquês',
  Dutch: 'Holandês',
  Estonian: 'Estoniano',
  Filipino: 'Filipino',
  Finnish: 'Finlandês',
  French: 'Francês',
  German: 'Alemão',
  Greek: 'Grego',
  Hebrew: 'Hebraico',
  Hindi: 'Hindi',
  Hungarian: 'Húngaro',
  Indonesian: 'Indonésio',
  Irish: 'Irlandês',
  Italian: 'Italiano',
  Japanese: 'Japonês',
  Korean: 'Coreano',
  Norwegian: 'Norueguês',
  Polish: 'Polonês',
  Portuguese: 'Português',
  Romanian: 'Romeno',
  Russian: 'Russo',
  Serbian: 'Sérvio',
  Slovak: 'Eslovaco',
  Slovenian: 'Esloveno',
  Spanish: 'Espanhol',
  Swedish: 'Sueco',
  Thai: 'Tailandês',
  Turkish: 'Turco',
  Ukrainian: 'Ucraniano',
  Vietnamese: 'Vietnamita',
};
const languageNameNl = {
  English: 'Engels',
  Arabic: 'Arabisch',
  Bengali: 'Bengalees',
  Bosnian: 'Bosnisch',
  Bulgarian: 'Bulgaars',
  Chinese: 'Chinees',
  Croatian: 'Kroatisch',
  Czech: 'Tsjechisch',
  Danish: 'Deens',
  Dutch: 'Nederlands',
  Estonian: 'Estisch',
  Filipino: 'Filipijns',
  Finnish: 'Fins',
  French: 'Frans',
  German: 'Duits',
  Greek: 'Grieks',
  Hebrew: 'Hebreeuws',
  Hindi: 'Hindi',
  Hungarian: 'Hongaars',
  Indonesian: 'Indonesisch',
  Irish: 'Iers',
  Italian: 'Italiaans',
  Japanese: 'Japans',
  Korean: 'Koreaans',
  Norwegian: 'Noors',
  Polish: 'Pools',
  Portuguese: 'Portugees',
  Romanian: 'Roemeens',
  Russian: 'Russisch',
  Serbian: 'Servisch',
  Slovak: 'Slovaaks',
  Slovenian: 'Sloveens',
  Spanish: 'Spaans',
  Swedish: 'Zweeds',
  Thai: 'Thai',
  Turkish: 'Turks',
  Ukrainian: 'Oekraïens',
  Vietnamese: 'Vietnamees',
};
const languageNameTr = {
  English: 'İngilizce',
  Arabic: 'Arapça',
  Bengali: 'Bengalce',
  Bosnian: 'Boşnakça',
  Bulgarian: 'Bulgarca',
  Chinese: 'Çince',
  Croatian: 'Hırvatça',
  Czech: 'Çekçe',
  Danish: 'Danca',
  Dutch: 'Felemenkçe',
  Estonian: 'Estçe',
  Filipino: 'Filipince',
  Finnish: 'Fince',
  French: 'Fransızca',
  German: 'Almanca',
  Greek: 'Yunanca',
  Hebrew: 'İbranice',
  Hindi: 'Hintçe',
  Hungarian: 'Macarca',
  Indonesian: 'Endonezce',
  Irish: 'İrlandaca',
  Italian: 'İtalyanca',
  Japanese: 'Japonca',
  Korean: 'Korece',
  Norwegian: 'Norveççe',
  Polish: 'Lehçe',
  Portuguese: 'Portekizce',
  Romanian: 'Rumence',
  Russian: 'Rusça',
  Serbian: 'Sırpça',
  Slovak: 'Slovakça',
  Slovenian: 'Slovence',
  Spanish: 'İspanyolca',
  Swedish: 'İsveççe',
  Thai: 'Tayca',
  Turkish: 'Türkçe',
  Ukrainian: 'Ukraynaca',
  Vietnamese: 'Vietnamca',
};
const languageNameJa = {
  English: '英語',
  Arabic: 'アラビア語',
  Bengali: 'ベンガル語',
  Chinese: '中国語',
  Danish: 'デンマーク語',
  Dutch: 'オランダ語',
  Finnish: 'フィンランド語',
  French: 'フランス語',
  German: 'ドイツ語',
  Greek: 'ギリシャ語',
  Hebrew: 'ヘブライ語',
  Hindi: 'ヒンディー語',
  Indonesian: 'インドネシア語',
  Italian: 'イタリア語',
  Japanese: '日本語',
  Korean: '韓国語',
  Norwegian: 'ノルウェー語',
  Polish: 'ポーランド語',
  Portuguese: 'ポルトガル語',
  Romanian: 'ルーマニア語',
  Russian: 'ロシア語',
  Spanish: 'スペイン語',
  Swedish: 'スウェーデン語',
  Thai: 'タイ語',
  Turkish: 'トルコ語',
  Ukrainian: 'ウクライナ語',
  Vietnamese: 'ベトナム語',
};
const languageNameKo = {
  English: '영어',
  Arabic: '아랍어',
  Chinese: '중국어',
  Danish: '덴마크어',
  Dutch: '네덜란드어',
  Finnish: '핀란드어',
  French: '프랑스어',
  German: '독일어',
  Greek: '그리스어',
  Hebrew: '히브리어',
  Hindi: '힌디어',
  Indonesian: '인도네시아어',
  Italian: '이탈리아어',
  Japanese: '일본어',
  Korean: '한국어',
  Norwegian: '노르웨이어',
  Polish: '폴란드어',
  Portuguese: '포르투갈어',
  Romanian: '루마니아어',
  Russian: '러시아어',
  Spanish: '스페인어',
  Swedish: '스웨덴어',
  Thai: '태국어',
  Turkish: '터키어',
  Ukrainian: '우크라이나어',
  Vietnamese: '베트남어',
};
const languageNameZh = {
  English: '英语',
  Arabic: '阿拉伯语',
  Chinese: '中文',
  Danish: '丹麦语',
  Dutch: '荷兰语',
  Finnish: '芬兰语',
  French: '法语',
  German: '德语',
  Greek: '希腊语',
  Hebrew: '希伯来语',
  Hindi: '印地语',
  Indonesian: '印尼语',
  Italian: '意大利语',
  Japanese: '日语',
  Korean: '韩语',
  Norwegian: '挪威语',
  Polish: '波兰语',
  Portuguese: '葡萄牙语',
  Romanian: '罗马尼亚语',
  Russian: '俄语',
  Spanish: '西班牙语',
  Swedish: '瑞典语',
  Thai: '泰语',
  Turkish: '土耳其语',
  Ukrainian: '乌克兰语',
  Vietnamese: '越南语',
};
const languageNameHi = {
  English: 'अंग्रेज़ी',
  Arabic: 'अरबी',
  Chinese: 'चीनी',
  French: 'फ्रेंच',
  German: 'जर्मन',
  Greek: 'यूनानी',
  Hebrew: 'हिब्रू',
  Hindi: 'हिंदी',
  Indonesian: 'इंडोनेशियाई',
  Italian: 'इतालवी',
  Japanese: 'जापानी',
  Korean: 'कोरियाई',
  Portuguese: 'पुर्तगाली',
  Russian: 'रूसी',
  Spanish: 'स्पेनिश',
  Thai: 'थाई',
  Turkish: 'तुर्की',
  Ukrainian: 'यूक्रेनियाई',
  Vietnamese: 'वियतनामी',
};
const languageNameDa = {
  English: 'Engelsk',
  Arabic: 'Arabisk',
  Chinese: 'Kinesisk',
  Danish: 'Dansk',
  Dutch: 'Hollandsk',
  Finnish: 'Finsk',
  French: 'Fransk',
  German: 'Tysk',
  Greek: 'Græsk',
  Hebrew: 'Hebraisk',
  Hindi: 'Hindi',
  Italian: 'Italiensk',
  Japanese: 'Japansk',
  Korean: 'Koreansk',
  Norwegian: 'Norsk',
  Polish: 'Polsk',
  Portuguese: 'Portugisisk',
  Romanian: 'Rumænsk',
  Russian: 'Russisk',
  Spanish: 'Spansk',
  Swedish: 'Svensk',
  Thai: 'Thai',
  Turkish: 'Tyrkisk',
  Ukrainian: 'Ukrainsk',
  Vietnamese: 'Vietnamesisk',
};
const languageNameSv = {
  English: 'Engelska',
  Arabic: 'Arabiska',
  Chinese: 'Kinesiska',
  Danish: 'Danska',
  Dutch: 'Nederländska',
  Finnish: 'Finska',
  French: 'Franska',
  German: 'Tyska',
  Greek: 'Grekiska',
  Hebrew: 'Hebreiska',
  Hindi: 'Hindi',
  Italian: 'Italienska',
  Japanese: 'Japanska',
  Korean: 'Koreanska',
  Norwegian: 'Norska',
  Polish: 'Polska',
  Portuguese: 'Portugisiska',
  Romanian: 'Rumänska',
  Russian: 'Ryska',
  Spanish: 'Spanska',
  Swedish: 'Svenska',
  Thai: 'Thailändska',
  Turkish: 'Turkiska',
  Ukrainian: 'Ukrainska',
  Vietnamese: 'Vietnamesiska',
};
const languageNameFi = {
  English: 'Englanti',
  Arabic: 'Arabia',
  Chinese: 'Kiina',
  Danish: 'Tanska',
  Dutch: 'Hollanti',
  Finnish: 'Suomi',
  French: 'Ranska',
  German: 'Saksa',
  Greek: 'Kreikka',
  Hebrew: 'Hebra',
  Hindi: 'Hindi',
  Italian: 'Italia',
  Japanese: 'Japani',
  Korean: 'Korea',
  Norwegian: 'Norja',
  Polish: 'Puola',
  Portuguese: 'Portugali',
  Romanian: 'Romania',
  Russian: 'Venäjä',
  Spanish: 'Espanja',
  Swedish: 'Ruotsi',
  Thai: 'Thai',
  Turkish: 'Turkki',
  Ukrainian: 'Ukraina',
  Vietnamese: 'Vietnam',
};
const languageNameNo = {
  English: 'Engelsk',
  Arabic: 'Arabisk',
  Chinese: 'Kinesisk',
  Danish: 'Dansk',
  Dutch: 'Nederlandsk',
  Finnish: 'Finsk',
  French: 'Fransk',
  German: 'Tysk',
  Greek: 'Gresk',
  Hebrew: 'Hebraisk',
  Hindi: 'Hindi',
  Italian: 'Italiensk',
  Japanese: 'Japansk',
  Korean: 'Koreansk',
  Norwegian: 'Norsk',
  Polish: 'Polsk',
  Portuguese: 'Portugisisk',
  Romanian: 'Rumensk',
  Russian: 'Russisk',
  Spanish: 'Spansk',
  Swedish: 'Svensk',
  Thai: 'Thai',
  Turkish: 'Tyrkisk',
  Ukrainian: 'Ukrainsk',
  Vietnamese: 'Vietnamesisk',
};
export const languageTranslations: Record<string, Record<string, string> | null> = {
  en: null,
  ru: languageNameRu,
  de: languageNameDe,
  fr: languageNameFr,
  es: languageNameEs,
  it: languageNameIt,
  pl: languageNamePl,
  pt_PT: languageNamePt,
  nl: languageNameNl,
  tr: languageNameTr,
  ja: languageNameJa,
  ko: languageNameKo,
  zh_CN: languageNameZh,
  hi: languageNameHi,
  da: languageNameDa,
  sv: languageNameSv,
  fi: languageNameFi,
  no: languageNameNo,
};

// Country code (ISO 3166-1 alpha-2) to full name - English base
export const countryNamesEn: Record<string, string> = {
  US: 'United States',
  GB: 'United Kingdom',
  AU: 'Australia',
  CA: 'Canada',
  ZA: 'South Africa',
  AE: 'United Arab Emirates',
  ET: 'Ethiopia',
  IN: 'India',
  SA: 'Saudi Arabia',
  DE: 'Germany',
  FR: 'France',
  ES: 'Spain',
  IT: 'Italy',
  PT: 'Portugal',
  PL: 'Poland',
  RU: 'Russia',
  NL: 'Netherlands',
  TR: 'Turkey',
  CN: 'China',
  JP: 'Japan',
  KR: 'South Korea',
  SE: 'Sweden',
  NO: 'Norway',
  DK: 'Denmark',
  FI: 'Finland',
  IL: 'Israel',
  AL: 'Albania',
  AZ: 'Azerbaijan',
  BA: 'Bosnia and Herzegovina',
  BG: 'Bulgaria',
  MM: 'Myanmar',
  HR: 'Croatia',
  CZ: 'Czech Republic',
  EE: 'Estonia',
  PH: 'Philippines',
  GE: 'Georgia',
  GR: 'Greece',
  HU: 'Hungary',
  IS: 'Iceland',
  ID: 'Indonesia',
  IE: 'Ireland',
  KZ: 'Kazakhstan',
  KH: 'Cambodia',
  LA: 'Laos',
  LV: 'Latvia',
  LT: 'Lithuania',
  MK: 'North Macedonia',
  MY: 'Malaysia',
  MT: 'Malta',
  MN: 'Mongolia',
  NP: 'Nepal',
  AF: 'Afghanistan',
  IR: 'Iran',
  RO: 'Romania',
  RS: 'Serbia',
  LK: 'Sri Lanka',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SO: 'Somalia',
  TH: 'Thailand',
  UA: 'Ukraine',
  UZ: 'Uzbekistan',
  VN: 'Vietnam',
  BD: 'Bangladesh',
  KE: 'Kenya',
  NG: 'Nigeria',
  GH: 'Ghana',
  TZ: 'Tanzania',
  NZ: 'New Zealand',
  SG: 'Singapore',
  HK: 'Hong Kong',
  PK: 'Pakistan',
  EG: 'Egypt',
  MA: 'Morocco',
  LB: 'Lebanon',
  JO: 'Jordan',
  KW: 'Kuwait',
  QA: 'Qatar',
  BH: 'Bahrain',
  OM: 'Oman',
  YE: 'Yemen',
  IQ: 'Iraq',
  SY: 'Syria',
  LY: 'Libya',
  TN: 'Tunisia',
  DZ: 'Algeria',
  PS: 'Palestine',
  RW: 'Rwanda',
  UG: 'Uganda',
  ZW: 'Zimbabwe',
  BW: 'Botswana',
  NA: 'Namibia',
  MZ: 'Mozambique',
  ZM: 'Zambia',
  MW: 'Malawi',
  SS: 'South Sudan',
  SD: 'Sudan',
  MU: 'Mauritius',
  SC: 'Seychelles',
  CY: 'Cyprus',
  LU: 'Luxembourg',
  AT: 'Austria',
  CH: 'Switzerland',
  BE: 'Belgium',
  PR: 'Puerto Rico',
  CO: 'Colombia',
  AR: 'Argentina',
  BR: 'Brazil',
  MX: 'Mexico',
  CL: 'Chile',
  PE: 'Peru',
  EC: 'Ecuador',
  VE: 'Venezuela',
  HN: 'Honduras',
  GT: 'Guatemala',
  CR: 'Costa Rica',
  PA: 'Panama',
  DO: 'Dominican Republic',
  CU: 'Cuba',
  JM: 'Jamaica',
  TT: 'Trinidad and Tobago',
  BS: 'Bahamas',
  AM: 'Armenia',
  BO: 'Bolivia',
  GQ: 'Equatorial Guinea',
  NI: 'Nicaragua',
  PY: 'Paraguay',
  SV: 'El Salvador',
  UY: 'Uruguay',
  TW: 'Taiwan',
};

// Country name translations by interface locale
const countryNamesRu = {
  US: 'США',
  GB: 'Великобритания',
  AU: 'Австралия',
  CA: 'Канада',
  ZA: 'ЮАР',
  AE: 'ОАЭ',
  ET: 'Эфиопия',
  IN: 'Индия',
  SA: 'Саудовская Аравия',
  DE: 'Германия',
  FR: 'Франция',
  ES: 'Испания',
  IT: 'Италия',
  PT: 'Португалия',
  PL: 'Польша',
  RU: 'Россия',
  NL: 'Нидерланды',
  TR: 'Турция',
  CN: 'Китай',
  JP: 'Япония',
  KR: 'Южная Корея',
  SE: 'Швеция',
  NO: 'Норвегия',
  DK: 'Дания',
  FI: 'Финляндия',
  IL: 'Израиль',
  BA: 'Босния и Герцеговина',
  BG: 'Болгария',
  CZ: 'Чехия',
  EE: 'Эстония',
  PH: 'Филиппины',
  GR: 'Греция',
  HU: 'Венгрия',
  KZ: 'Казахстан',
  LV: 'Латвия',
  LT: 'Литва',
  RO: 'Румыния',
  RS: 'Сербия',
  SK: 'Словакия',
  SI: 'Словения',
  TH: 'Таиланд',
  UA: 'Украина',
  VN: 'Вьетнам',
  BD: 'Бангладеш',
  NZ: 'Новая Зеландия',
  SG: 'Сингапур',
  PK: 'Пакистан',
  EG: 'Египет',
  AT: 'Австрия',
  CH: 'Швейцария',
  BE: 'Бельгия',
  CO: 'Колумбия',
  AR: 'Аргентина',
  BR: 'Бразилия',
  MX: 'Мексика',
  CL: 'Чили',
  PE: 'Перу',
  UZ: 'Узбекистан',
  AL: 'Албания',
  AZ: 'Азербайджан',
  MM: 'Мьянма',
  HR: 'Хорватия',
  GE: 'Грузия',
  ID: 'Индонезия',
  IE: 'Ирландия',
  KH: 'Камбоджа',
  LA: 'Лаос',
  MK: 'Северная Македония',
  MY: 'Малайзия',
  MT: 'Мальта',
  MN: 'Монголия',
  NP: 'Непал',
  AF: 'Афганистан',
  IR: 'Иран',
  LK: 'Шри-Ланка',
  SO: 'Сомали',
  MA: 'Марокко',
  LB: 'Ливан',
  JO: 'Иордания',
  KW: 'Кувейт',
  QA: 'Катар',
  BH: 'Бахрейн',
  OM: 'Оман',
  YE: 'Йемен',
  IQ: 'Ирак',
  SY: 'Сирия',
  LY: 'Ливия',
  TN: 'Тунис',
  DZ: 'Алжир',
  PS: 'Палестина',
  RW: 'Руанда',
  UG: 'Уганда',
  ZW: 'Зимбабве',
  BW: 'Ботсвана',
  NA: 'Намибия',
  MZ: 'Мозамбик',
  ZM: 'Замбия',
  MW: 'Малави',
  KE: 'Кения',
  NG: 'Нигерия',
  GH: 'Гана',
  TZ: 'Танзания',
  HK: 'Гонконг',
  LU: 'Люксембург',
  PR: 'Пуэрто-Рико',
  EC: 'Эквадор',
  VE: 'Венесуэла',
  HN: 'Гондурас',
  GT: 'Гватемала',
  CR: 'Коста-Рика',
  PA: 'Панама',
  DO: 'Доминиканская Республика',
  CU: 'Куба',
  JM: 'Ямайка',
  TT: 'Тринидад и Тобаго',
  BS: 'Багамы',
  AM: 'Армения',
  BO: 'Боливия',
  GQ: 'Экваториальная Гвинея',
  NI: 'Никарагуа',
  PY: 'Парагвай',
  SV: 'Сальвадор',
  UY: 'Уругвай',
  TW: 'Тайвань',
  CY: 'Кипр',
  MU: 'Маврикий',
  SC: 'Сейшелы',
  SS: 'Южный Судан',
  SD: 'Судан',
};
const countryNamesDe = {
  US: 'Vereinigte Staaten',
  GB: 'Vereinigtes Königreich',
  AU: 'Australien',
  CA: 'Kanada',
  ZA: 'Südafrika',
  AE: 'Vereinigte Arabische Emirate',
  IN: 'Indien',
  DE: 'Deutschland',
  FR: 'Frankreich',
  ES: 'Spanien',
  IT: 'Italien',
  PT: 'Portugal',
  PL: 'Polen',
  RU: 'Russland',
  NL: 'Niederlande',
  TR: 'Türkei',
  CN: 'China',
  JP: 'Japan',
  KR: 'Südkorea',
  SE: 'Schweden',
  NO: 'Norwegen',
  DK: 'Dänemark',
  FI: 'Finnland',
  IL: 'Israel',
  AT: 'Österreich',
  CH: 'Schweiz',
  BE: 'Belgien',
  GR: 'Griechenland',
  IE: 'Irland',
  NZ: 'Neuseeland',
  SG: 'Singapur',
  HK: 'Hongkong',
  MX: 'Mexiko',
  BR: 'Brasilien',
  AR: 'Argentinien',
  CL: 'Chile',
  CO: 'Kolumbien',
  PE: 'Peru',
};
const countryNamesFr = {
  US: 'États-Unis',
  GB: 'Royaume-Uni',
  AU: 'Australie',
  CA: 'Canada',
  ZA: 'Afrique du Sud',
  AE: 'Émirats arabes unis',
  IN: 'Inde',
  FR: 'France',
  DE: 'Allemagne',
  ES: 'Espagne',
  IT: 'Italie',
  PT: 'Portugal',
  PL: 'Pologne',
  RU: 'Russie',
  NL: 'Pays-Bas',
  TR: 'Turquie',
  CN: 'Chine',
  JP: 'Japon',
  KR: 'Corée du Sud',
  SE: 'Suède',
  NO: 'Norvège',
  DK: 'Danemark',
  FI: 'Finlande',
  IL: 'Israël',
  AT: 'Autriche',
  CH: 'Suisse',
  BE: 'Belgique',
  GR: 'Grèce',
  IE: 'Irlande',
  NZ: 'Nouvelle-Zélande',
  SG: 'Singapour',
  MX: 'Mexique',
  BR: 'Brésil',
  AR: 'Argentine',
  CL: 'Chili',
  CO: 'Colombie',
  PE: 'Pérou',
};
const countryNamesEs = {
  US: 'Estados Unidos',
  GB: 'Reino Unido',
  AU: 'Australia',
  CA: 'Canadá',
  ZA: 'Sudáfrica',
  AE: 'Emiratos Árabes Unidos',
  IN: 'India',
  ES: 'España',
  DE: 'Alemania',
  FR: 'Francia',
  IT: 'Italia',
  PT: 'Portugal',
  PL: 'Polonia',
  RU: 'Rusia',
  NL: 'Países Bajos',
  TR: 'Turquía',
  CN: 'China',
  JP: 'Japón',
  KR: 'Corea del Sur',
  SE: 'Suecia',
  NO: 'Noruega',
  DK: 'Dinamarca',
  FI: 'Finlandia',
  IL: 'Israel',
  AT: 'Austria',
  CH: 'Suiza',
  BE: 'Bélgica',
  GR: 'Grecia',
  IE: 'Irlanda',
  NZ: 'Nueva Zelanda',
  SG: 'Singapur',
  MX: 'México',
  BR: 'Brasil',
  AR: 'Argentina',
  CL: 'Chile',
  CO: 'Colombia',
  PE: 'Perú',
};
const countryNamesIt = {
  US: 'Stati Uniti',
  GB: 'Regno Unito',
  AU: 'Australia',
  CA: 'Canada',
  ZA: 'Sudafrica',
  AE: 'Emirati Arabi Uniti',
  IN: 'India',
  IT: 'Italia',
  DE: 'Germania',
  FR: 'Francia',
  ES: 'Spagna',
  PT: 'Portogallo',
  PL: 'Polonia',
  RU: 'Russia',
  NL: 'Paesi Bassi',
  TR: 'Turchia',
  CN: 'Cina',
  JP: 'Giappone',
  KR: 'Corea del Sud',
  SE: 'Svezia',
  NO: 'Norvegia',
  DK: 'Danimarca',
  FI: 'Finlandia',
  IL: 'Israele',
  AT: 'Austria',
  CH: 'Svizzera',
  BE: 'Belgio',
  GR: 'Grecia',
  IE: 'Irlanda',
  NZ: 'Nuova Zelanda',
  SG: 'Singapore',
  MX: 'Messico',
  BR: 'Brasile',
  AR: 'Argentina',
  CL: 'Cile',
  CO: 'Colombia',
  PE: 'Perù',
};
const countryNamesPl = {
  US: 'Stany Zjednoczone',
  GB: 'Wielka Brytania',
  AU: 'Australia',
  CA: 'Kanada',
  ZA: 'Republika Południowej Afryki',
  IN: 'Indie',
  DE: 'Niemcy',
  FR: 'Francja',
  ES: 'Hiszpania',
  IT: 'Włochy',
  PT: 'Portugalia',
  PL: 'Polska',
  RU: 'Rosja',
  NL: 'Holandia',
  TR: 'Turcja',
  CN: 'Chiny',
  JP: 'Japonia',
  KR: 'Korea Południowa',
  SE: 'Szwecja',
  NO: 'Norwegia',
  DK: 'Dania',
  FI: 'Finlandia',
  IL: 'Izrael',
  AT: 'Austria',
  CH: 'Szwajcaria',
  BE: 'Belgia',
  GR: 'Grecja',
  IE: 'Irlandia',
  NZ: 'Nowa Zelandia',
  SG: 'Singapur',
  MX: 'Meksyk',
  BR: 'Brazylia',
  AR: 'Argentyna',
  CL: 'Chile',
  CO: 'Kolumbia',
  PE: 'Peru',
};
const countryNamesPt = {
  US: 'Estados Unidos',
  GB: 'Reino Unido',
  AU: 'Austrália',
  CA: 'Canadá',
  ZA: 'África do Sul',
  AE: 'Emirados Árabes Unidos',
  IN: 'Índia',
  PT: 'Portugal',
  DE: 'Alemanha',
  FR: 'França',
  ES: 'Espanha',
  IT: 'Itália',
  PL: 'Polônia',
  RU: 'Rússia',
  NL: 'Países Baixos',
  TR: 'Turquia',
  CN: 'China',
  JP: 'Japão',
  KR: 'Coreia do Sul',
  SE: 'Suécia',
  NO: 'Noruega',
  DK: 'Dinamarca',
  FI: 'Finlândia',
  IL: 'Israel',
  AT: 'Áustria',
  CH: 'Suíça',
  BE: 'Bélgica',
  GR: 'Grécia',
  IE: 'Irlanda',
  NZ: 'Nova Zelândia',
  SG: 'Singapura',
  MX: 'México',
  BR: 'Brasil',
  AR: 'Argentina',
  CL: 'Chile',
  CO: 'Colômbia',
  PE: 'Peru',
};
const countryNamesNl = {
  US: 'Verenigde Staten',
  GB: 'Verenigd Koninkrijk',
  AU: 'Australië',
  CA: 'Canada',
  ZA: 'Zuid-Afrika',
  AE: 'Verenigde Arabische Emiraten',
  IN: 'India',
  DE: 'Duitsland',
  FR: 'Frankrijk',
  ES: 'Spanje',
  IT: 'Italië',
  PT: 'Portugal',
  PL: 'Polen',
  RU: 'Rusland',
  NL: 'Nederland',
  TR: 'Turkije',
  CN: 'China',
  JP: 'Japan',
  KR: 'Zuid-Korea',
  SE: 'Zweden',
  NO: 'Noorwegen',
  DK: 'Denemarken',
  FI: 'Finland',
  IL: 'Israël',
  AT: 'Oostenrijk',
  CH: 'Zwitserland',
  BE: 'België',
  GR: 'Griekenland',
  IE: 'Ierland',
  NZ: 'Nieuw-Zeeland',
  SG: 'Singapore',
  MX: 'Mexico',
  BR: 'Brazilië',
  AR: 'Argentinië',
  CL: 'Chili',
  CO: 'Colombia',
  PE: 'Peru',
};
const countryNamesTr = {
  US: 'ABD',
  GB: 'Birleşik Krallık',
  AU: 'Avustralya',
  CA: 'Kanada',
  ZA: 'Güney Afrika',
  AE: 'BAE',
  IN: 'Hindistan',
  DE: 'Almanya',
  FR: 'Fransa',
  ES: 'İspanya',
  IT: 'İtalya',
  PT: 'Portekiz',
  PL: 'Polonya',
  RU: 'Rusya',
  NL: 'Hollanda',
  TR: 'Türkiye',
  CN: 'Çin',
  JP: 'Japonya',
  KR: 'Güney Kore',
  SE: 'İsveç',
  NO: 'Norveç',
  DK: 'Danimarka',
  FI: 'Finlandiya',
  IL: 'İsrail',
  AT: 'Avusturya',
  CH: 'İsviçre',
  BE: 'Belçika',
  GR: 'Yunanistan',
  IE: 'İrlanda',
  NZ: 'Yeni Zelanda',
  SG: 'Singapur',
  MX: 'Meksika',
  BR: 'Brezilya',
  AR: 'Arjantin',
  CL: 'Şili',
  CO: 'Kolombiya',
  PE: 'Peru',
};
const countryNamesJa = {
  US: 'アメリカ',
  GB: 'イギリス',
  AU: 'オーストラリア',
  CA: 'カナダ',
  ZA: '南アフリカ',
  AE: 'UAE',
  IN: 'インド',
  DE: 'ドイツ',
  FR: 'フランス',
  ES: 'スペイン',
  IT: 'イタリア',
  PT: 'ポルトガル',
  PL: 'ポーランド',
  RU: 'ロシア',
  NL: 'オランダ',
  TR: 'トルコ',
  CN: '中国',
  JP: '日本',
  KR: '韓国',
  SE: 'スウェーデン',
  NO: 'ノルウェー',
  DK: 'デンマーク',
  FI: 'フィンランド',
  IL: 'イスラエル',
  AT: 'オーストリア',
  CH: 'スイス',
  BE: 'ベルギー',
  GR: 'ギリシャ',
  IE: 'アイルランド',
  NZ: 'ニュージーランド',
  SG: 'シンガポール',
  MX: 'メキシコ',
  BR: 'ブラジル',
  AR: 'アルゼンチン',
  CL: 'チリ',
  CO: 'コロンビア',
  PE: 'ペルー',
  PH: 'フィリピン',
  HK: '香港',
  TW: '台湾',
};
const countryNamesKo = {
  US: '미국',
  GB: '영국',
  AU: '호주',
  CA: '캐나다',
  ZA: '남아프리카',
  AE: 'UAE',
  IN: '인도',
  DE: '독일',
  FR: '프랑스',
  ES: '스페인',
  IT: '이탈리아',
  PT: '포르투갈',
  PL: '폴란드',
  RU: '러시아',
  NL: '네덜란드',
  TR: '터키',
  CN: '중국',
  JP: '일본',
  KR: '대한민국',
  SE: '스웨덴',
  NO: '노르웨이',
  DK: '덴마크',
  FI: '핀란드',
  IL: '이스라엘',
  AT: '오스트리아',
  CH: '스위스',
  BE: '벨기에',
  GR: '그리스',
  IE: '아일랜드',
  NZ: '뉴질랜드',
  SG: '싱가포르',
  MX: '멕시코',
  BR: '브라질',
  AR: '아르헨티나',
  CL: '칠레',
  CO: '콜롬비아',
  PE: '페루',
  PH: '필리핀',
  HK: '홍콩',
  TW: '대만',
};
const countryNamesZh = {
  US: '美国',
  GB: '英国',
  AU: '澳大利亚',
  CA: '加拿大',
  ZA: '南非',
  AE: '阿联酋',
  IN: '印度',
  DE: '德国',
  FR: '法国',
  ES: '西班牙',
  IT: '意大利',
  PT: '葡萄牙',
  PL: '波兰',
  RU: '俄罗斯',
  NL: '荷兰',
  TR: '土耳其',
  CN: '中国',
  JP: '日本',
  KR: '韩国',
  SE: '瑞典',
  NO: '挪威',
  DK: '丹麦',
  FI: '芬兰',
  IL: '以色列',
  AT: '奥地利',
  CH: '瑞士',
  BE: '比利时',
  GR: '希腊',
  IE: '爱尔兰',
  NZ: '新西兰',
  SG: '新加坡',
  MX: '墨西哥',
  BR: '巴西',
  AR: '阿根廷',
  CL: '智利',
  CO: '哥伦比亚',
  PE: '秘鲁',
  PH: '菲律宾',
  HK: '香港',
  TW: '台湾',
};
const countryNamesHi = {
  US: 'अमेरिका',
  GB: 'ब्रिटेन',
  AU: 'ऑस्ट्रेलिया',
  CA: 'कनाडा',
  IN: 'भारत',
  DE: 'जर्मनी',
  FR: 'फ्रांस',
  ES: 'स्पेन',
  IT: 'इटली',
  PT: 'पुर्तगाल',
  PL: 'पोलैंड',
  RU: 'रूस',
  NL: 'नीदरलैंड',
  TR: 'तुर्की',
  CN: 'चीन',
  JP: 'जापान',
  KR: 'दक्षिण कोरिया',
  SE: 'स्वीडन',
  NO: 'नॉर्वे',
  DK: 'डेनमार्क',
  FI: 'फिनलैंड',
  IL: 'इज़राइल',
  IE: 'आयरलैंड',
  NZ: 'न्यूजीलैंड',
  SG: 'सिंगापुर',
  MX: 'मेक्सिको',
  BR: 'ब्राजील',
  AR: 'अर्जेंटीना',
  PH: 'फिलीपींस',
};
const countryNamesDa = {
  US: 'USA',
  GB: 'Storbritannien',
  AU: 'Australien',
  CA: 'Canada',
  ZA: 'Sydafrika',
  IN: 'Indien',
  DE: 'Tyskland',
  FR: 'Frankrig',
  ES: 'Spanien',
  IT: 'Italien',
  PT: 'Portugal',
  PL: 'Polen',
  RU: 'Rusland',
  NL: 'Holland',
  TR: 'Tyrkiet',
  CN: 'Kina',
  JP: 'Japan',
  KR: 'Sydkorea',
  SE: 'Sverige',
  NO: 'Norge',
  DK: 'Danmark',
  FI: 'Finland',
  IL: 'Israel',
  AT: 'Østrig',
  CH: 'Schweiz',
  BE: 'Belgien',
  IE: 'Irland',
  NZ: 'New Zealand',
  SG: 'Singapore',
  MX: 'Mexico',
  BR: 'Brasilien',
  AR: 'Argentina',
  CL: 'Chile',
  PE: 'Peru',
};
const countryNamesSv = {
  US: 'USA',
  GB: 'Storbritannien',
  AU: 'Australien',
  CA: 'Kanada',
  ZA: 'Sydafrika',
  IN: 'Indien',
  DE: 'Tyskland',
  FR: 'Frankrike',
  ES: 'Spanien',
  IT: 'Italien',
  PT: 'Portugal',
  PL: 'Polen',
  RU: 'Ryssland',
  NL: 'Nederländerna',
  TR: 'Turkiet',
  CN: 'Kina',
  JP: 'Japan',
  KR: 'Sydkorea',
  SE: 'Sverige',
  NO: 'Norge',
  DK: 'Danmark',
  FI: 'Finland',
  IL: 'Israel',
  AT: 'Österrike',
  CH: 'Schweiz',
  BE: 'Belgien',
  IE: 'Irland',
  NZ: 'Nya Zeeland',
  SG: 'Singapore',
  MX: 'Mexiko',
  BR: 'Brasilien',
  AR: 'Argentina',
  CL: 'Chile',
  PE: 'Peru',
};
const countryNamesFi = {
  US: 'USA',
  GB: 'Iso-Britannia',
  AU: 'Australia',
  CA: 'Kanada',
  ZA: 'Etelä-Afrikka',
  IN: 'Intia',
  DE: 'Saksa',
  FR: 'Ranska',
  ES: 'Espanja',
  IT: 'Italia',
  PT: 'Portugali',
  PL: 'Puola',
  RU: 'Venäjä',
  NL: 'Alankomaat',
  TR: 'Turkki',
  CN: 'Kiina',
  JP: 'Japani',
  KR: 'Etelä-Korea',
  SE: 'Ruotsi',
  NO: 'Norja',
  DK: 'Tanska',
  FI: 'Suomi',
  IL: 'Israel',
  AT: 'Itävalta',
  CH: 'Sveitsi',
  BE: 'Belgia',
  IE: 'Irlanti',
  NZ: 'Uusi-Seelanti',
  SG: 'Singapore',
  MX: 'Meksiko',
  BR: 'Brasilia',
  AR: 'Argentiina',
  CL: 'Chile',
  PE: 'Peru',
};
const countryNamesNo = {
  US: 'USA',
  GB: 'Storbritannia',
  AU: 'Australia',
  CA: 'Canada',
  ZA: 'Sør-Afrika',
  IN: 'India',
  DE: 'Tyskland',
  FR: 'Frankrike',
  ES: 'Spania',
  IT: 'Italia',
  PT: 'Portugal',
  PL: 'Polen',
  RU: 'Russland',
  NL: 'Nederland',
  TR: 'Tyrkia',
  CN: 'Kina',
  JP: 'Japan',
  KR: 'Sør-Korea',
  SE: 'Sverige',
  NO: 'Norge',
  DK: 'Danmark',
  FI: 'Finland',
  IL: 'Israel',
  AT: 'Østerrike',
  CH: 'Sveits',
  BE: 'Belgia',
  IE: 'Irland',
  NZ: 'New Zealand',
  SG: 'Singapore',
  MX: 'Mexico',
  BR: 'Brasil',
  AR: 'Argentina',
  CL: 'Chile',
  PE: 'Peru',
};
export const countryTranslations: Record<string, Record<string, string>> = {
  en: countryNamesEn,
  ru: countryNamesRu,
  de: countryNamesDe,
  fr: countryNamesFr,
  es: countryNamesEs,
  it: countryNamesIt,
  pl: countryNamesPl,
  pt_PT: countryNamesPt,
  nl: countryNamesNl,
  tr: countryNamesTr,
  ja: countryNamesJa,
  ko: countryNamesKo,
  zh_CN: countryNamesZh,
  hi: countryNamesHi,
  da: countryNamesDa,
  sv: countryNamesSv,
  fi: countryNamesFi,
  no: countryNamesNo,
};

// Gender translations by interface locale
export const genderTranslations: Record<string, Record<string, string>> = {
  en: { Male: 'Male', Female: 'Female' },
  ru: { Male: 'Мужской', Female: 'Женский' },
  de: { Male: 'Männlich', Female: 'Weiblich' },
  fr: { Male: 'Homme', Female: 'Femme' },
  es: { Male: 'Masculino', Female: 'Femenino' },
  it: { Male: 'Maschio', Female: 'Femmina' },
  pl: { Male: 'Mężczyzna', Female: 'Kobieta' },
  pt_PT: { Male: 'Masculino', Female: 'Feminino' },
  nl: { Male: 'Man', Female: 'Vrouw' },
  tr: { Male: 'Erkek', Female: 'Kadın' },
  ja: { Male: '男性', Female: '女性' },
  ko: { Male: '남성', Female: '여성' },
  zh_CN: { Male: '男', Female: '女' },
  hi: { Male: 'पुरुष', Female: 'महिला' },
  da: { Male: 'Mand', Female: 'Kvinde' },
  sv: { Male: 'Man', Female: 'Kvinna' },
  fi: { Male: 'Mies', Female: 'Nainen' },
  no: { Male: 'Mann', Female: 'Kvinne' },
};
